/** Placeholder samples until uploads / CMS are wired. */

export const SAMPLE_LIBRARY_CATEGORIES = [
  { id: "pro", label: "Pro" },
  { id: "business", label: "Business" },
  { id: "programming", label: "Programming" },
  { id: "engineering", label: "Engineering" },
  { id: "marketing", label: "Marketing" },
  { id: "design", label: "Design" },
  { id: "student", label: "Student" },
  { id: "medical", label: "Medical" },
  { id: "finance", label: "Finance" },
  { id: "education", label: "Education" },
  { id: "legal", label: "Legal" },
  { id: "other", label: "Other" },
];

/** @type {{ id: string; company: string; role: string; category: string; isPro: boolean; accent: string }[]} */
export const MOCK_SAMPLE_LIBRARY = [
  {
    id: "chime-pm",
    company: "Chime",
    role: "Project Manager",
    category: "pro",
    isPro: true,
    accent: "#1d4ed8",
  },
  {
    id: "disney-program",
    company: "Disney",
    role: "Disney College Program",
    category: "business",
    isPro: true,
    accent: "#0284c7",
  },
  {
    id: "adidas-spm",
    company: "Adidas",
    role: "Senior Project Manager",
    category: "marketing",
    isPro: true,
    accent: "#0d9488",
  },
  {
    id: "sony-grad",
    company: "Sony",
    role: "Corporate Rotational Graduate",
    category: "business",
    isPro: true,
    accent: "#4f46e5",
  },
  {
    id: "accenture-intern",
    company: "Accenture",
    role: "Assistant Policy Intern",
    category: "legal",
    isPro: true,
    accent: "#b45309",
  },
  {
    id: "deloitte-ba",
    company: "Deloitte",
    role: "Senior Business Analyst",
    category: "finance",
    isPro: true,
    accent: "#0369a1",
  },
  {
    id: "ncstate-security",
    company: "NC State",
    role: "IT Security Architect",
    category: "engineering",
    isPro: true,
    accent: "#7c3aed",
  },
  {
    id: "meta-de",
    company: "Facebook",
    role: "Data Engineer",
    category: "programming",
    isPro: true,
    accent: "#2563eb",
  },
  {
    id: "sap-dev",
    company: "SAP",
    role: "SAP Developer",
    category: "programming",
    isPro: true,
    accent: "#0f766e",
  },
  {
    id: "hubspot-swe",
    company: "HubSpot",
    role: "Software Developer",
    category: "programming",
    isPro: false,
    accent: "#ea580c",
  },
  {
    id: "tesla-producer",
    company: "Tesla",
    role: "Creative Producer",
    category: "design",
    isPro: true,
    accent: "#b91c1c",
  },
  {
    id: "ea-analyst",
    company: "Electronic Arts",
    role: "Senior Data Analyst",
    category: "marketing",
    isPro: true,
    accent: "#15803d",
  },
  {
    id: "student-swe",
    company: "Campus role",
    role: "Computer Science · Intern",
    category: "student",
    isPro: false,
    accent: "#6d28d9",
  },
  {
    id: "medical-scribe",
    company: "Regional Health",
    role: "Medical Scribe",
    category: "medical",
    isPro: false,
    accent: "#0e7490",
  },
  {
    id: "ed-teacher",
    company: "Lincoln High School",
    role: "English Teacher",
    category: "education",
    isPro: false,
    accent: "#c2410c",
  },
  {
    id: "other-coord",
    company: "Local nonprofit",
    role: "Operations Coordinator",
    category: "other",
    isPro: false,
    accent: "#57534e",
  },
];
